Added a code to check the existence of swig command in "config/swig.m4".

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4202,6 +4202,12 @@ fi
 
     if test -n "$SWIG";
     then
+        if test $SWIG != "swig" && ! test -f $SWIG;
+        then
+          { { echo "$as_me:$LINENO: error: *** $SWIG missing - please install first or check config.log ***" >&5
+echo "$as_me: error: *** $SWIG missing - please install first or check config.log ***" >&2;}
+   { (exit 1); exit 1; }; }
+        fi
         SWIGLIB=`"$SWIG" -swiglib`
 
 
@@ -5728,7 +5734,7 @@ if test "${ac_cv_FUNC_LISPEXIT+set}" = set; then
 else
   ac_cv_FUNC_LISPEXIT=no-exit
     for ex in "sb-ext:quit :unix-status" "lisp:exit" "excl:exit" "sys:exit" "ext:quit" "unix:unix-exit" "no-exit" ; do
-      echo "configure:5731 trying $ex ..." >&5
+      echo "configure:5737 trying $ex ..." >&5
       echo "(ignore-errors ($ex 127))"|$LISP 2>&5 1>&5
       if test "$?" = "127" ; then
         ac_cv_FUNC_LISPEXIT=$ex
