Rebuilt after changes to config/*.m4 files.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4113,7 +4113,7 @@ echo $ECHO_N "checking $JAVA version >= 1.4.0... $ECHO_C" >&6
 	rx=`echo 1.4.0 | sed -e 's/\([0-9]\)\.\([0-9]\)\.\([0-9]\).*/\1/'`
 	ry=`echo 1.4.0 | sed -e 's/\([0-9]\)\.\([0-9]\)\.\([0-9]\).*/\2/'`
 	rz=`echo 1.4.0 | sed -e 's/\([0-9]\)\.\([0-9]\)\.\([0-9]\).*/\3/'`
-	version=`$JAVA -version 2>&1 | head -1`
+	version=`$JAVA -version 2>&1 | sed -e 's/\(.*\)$/\1/;q'`
 	jx=`echo $version | sed -e 's/java version \"\([0-9]\)\.\([0-9]\)\.\([0-9]\).*/\1/'`
 	jy=`echo $version | sed -e 's/java version \"\([0-9]\)\.\([0-9]\)\.\([0-9]\).*/\2/'`
 	jz=`echo $version | sed -e 's/java version \"\([0-9]\)\.\([0-9]\)\.\([0-9]\).*/\3/'`
@@ -4148,15 +4148,11 @@ echo "$as_me: error: '$JAVAC' undefined" >&2;}
 
     _cur=""$JAVAC""
   while ls -ld "$_cur" 2>/dev/null | grep " -> " >/dev/null; do
-        echo "$as_me:$LINENO: checking symlink for $_cur" >&5
-echo $ECHO_N "checking symlink for $_cur... $ECHO_C" >&6
         _slink=`ls -ld "$_cur" | sed 's/.* -> //'`
         case "$_slink" in
           /*) _cur="$_slink";;
                     *) _cur=`echo "X$_cur" | sed -e 's/^X//' -e 's:[^/]*$::'`"$_slink";;
         esac
-        echo "$as_me:$LINENO: result: $_cur" >&5
-echo "${ECHO_T}$_cur" >&6
   done
   JAVA_FOLLOWED="$_cur"
 
@@ -4166,6 +4162,17 @@ echo "${ECHO_T}$_cur" >&6
 	java_bail=no
 	java_mac_prefix="/System/Library/Frameworks/JavaVM.framework"
 	case $JAVA_VER_MINOR in
+	  6)
+	    if test -e "$java_mac_prefix/Versions/CurrentJDK/Headers"; then
+	      _jinc="$java_mac_prefix/Versions/CurrentJDK/Headers"
+	    elif test -e "$java_mac_prefix/Versions/1.6.0/Headers"; then
+	      _jinc="$java_mac_prefix/Versions/1.6.0/Headers"
+	    elif test -e "$java_mac_prefix/Versions/1.6/Headers"; then
+	      _jinc="$java_mac_prefix/Versions/1.6/Headers"
+	    else
+	      java_bail=yes
+	    fi
+	    ;;
 	  5)
 	    if test -e "$java_mac_prefix/Versions/CurrentJDK/Headers"; then
 	      _jinc="$java_mac_prefix/Versions/CurrentJDK/Headers"
@@ -4632,7 +4639,7 @@ if test "${ac_cv_FUNC_LISPEXIT+set}" = set; then
 else
   ac_cv_FUNC_LISPEXIT=no-exit
     for ex in "sb-ext:quit :unix-status" "lisp:exit" "excl:exit" "sys:exit" "ext:quit" "unix:unix-exit" "no-exit" ; do
-      echo "configure:4635 trying $ex ..." >&5
+      echo "configure:4642 trying $ex ..." >&5
       echo "(ignore-errors ($ex 127))"|$LISP 2>&5 1>&5
       if test "$?" = "127" ; then
         ac_cv_FUNC_LISPEXIT=$ex
@@ -5677,15 +5684,53 @@ fi;
 
     if test $with_libxml != yes; then
       xml_config_args="$xml_config_args --prefix=$with_libxml"
-      if test x${XML2_CONFIG+set} != xset ; then
-        XML2_CONFIG=$with_libxml/bin/xml2-config
+      if test -n "$XML2_CONFIG" ; then
+	        XML2_CONFIG=$with_libxml/bin/xml2-config
+      else
+        	        # Extract the first word of "xml2-config", so it can be a program name with args.
+set dummy xml2-config; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_XML2_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $XML2_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_XML2_CONFIG="$XML2_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $with_libxml/bin
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_XML2_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_XML2_CONFIG" && ac_cv_path_XML2_CONFIG="no"
+  ;;
+esac
+fi
+XML2_CONFIG=$ac_cv_path_XML2_CONFIG
+
+if test -n "$XML2_CONFIG"; then
+  echo "$as_me:$LINENO: result: $XML2_CONFIG" >&5
+echo "${ECHO_T}$XML2_CONFIG" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
       fi
-    fi
-
-    ac_save_CPPFLAGS="$CPPFLAGS"
-    ac_save_LIBS="$LIBS"
-
-    # Extract the first word of "xml2-config", so it can be a program name with args.
+    else
+            if test x${XML2_CONFIG+set} != xset ; then
+                # Extract the first word of "xml2-config", so it can be a program name with args.
 set dummy xml2-config; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
@@ -5724,6 +5769,23 @@ else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
+
+      fi
+    fi
+
+    ac_save_CPPFLAGS="$CPPFLAGS"
+    ac_save_LIBS="$LIBS"
+
+    if test "$XML2_CONFIG" = "no"; then
+      echo "*** Could not find 'xml2-config' in directory $with_libxml/bin/."
+      echo "*** Please check that the PATH supplied to --with-libxml=PATH"
+      echo "*** is of the form '/usr/local' and not '/usr/local/lib'; in"
+      echo "*** other words, omit the 'lib' part of the name.  The 'configure'"
+      echo "*** utility will append 'lib' to the given path automatically."
+      { { echo "$as_me:$LINENO: error: could not find xml2-config in $with_libxml/bin" >&5
+echo "$as_me: error: could not find xml2-config in $with_libxml/bin" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
 
     min_xml_version=2.0.0
     echo "$as_me:$LINENO: checking for libxml2 - version >= $min_xml_version" >&5
