The flag --with-swig now acts like the other --with-foo flags: it lets the user specify where to find the desired copy of swig.  This is in contrast to what was happening before, which was that if --with-swig was given, it meant also to force reswig'ing in some cases.
If --with-swig is not given but configure detects that it
will be needed to build the bindings, it will look for swig
on the user's /Users/mhucka/system/i386-darwin98/bin /Users/mhucka/system/bin /usr/local/bin /usr/bin/X11 /usr/openwin/bin /usr/ucb /usr/bin /bin /sbin /usr/ccs/bin /usr/5bin /usr/sbin /usr/etc /etc /sw/bin /sw/sbin /Library/Frameworks/Python.framework/Versions/Current/bin /Developer/Tools /System/Library/CoreServices and test the version.

The new makefile changes basically tries to make things like
a more straightforward make dependency scheme, wherein it
always tests if libsbml_wrap.cpp is out of date and tries to
rebuild it if so.  Normally, re-swig'ing shouldn't be
necessary: as you know, in a distribution, the
libsbml_wrap.cpp will be up to date, so it shouldn't matter
to end users.  And the dependencies on source files means
that only if a source file is changed will it try to
re-swig, and that should happen only for developers who are
mucking with libsbml code (for whom it's ok to require
swig).

The tests for versions and consistency happen at both
configure time and compile time, to be (hopefully) more
robust.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1588,7 +1588,7 @@ Optional Packages:
   --with-csharp-compiler=path
                           Set location of CSharp compiler
                           [default=autodetect]
-  --with-swig=PREFIX      Regenerate SWIG wrappers [default=if_needed]
+  --with-swig=PREFIX      Set location of swig [default=autodetect]
   --with-doxygen=PREFIX   Specify path to doxygen [default=autodetect]
   --with-expat=PREFIX     Use Expat XML Library [default=no]
   --with-xerces=PREFIX    Use the Xerces XML Library [default=yes]
@@ -22800,6 +22800,44 @@ fi
 
 
 
+      { echo "$as_me:$LINENO: checking $SWIG version >= 1.3.40" >&5
+echo $ECHO_N "checking $SWIG version >= 1.3.40... $ECHO_C" >&6; }
+
+
+
+      rx=`echo 1.3.40 | sed -e 's/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*/\1/'`
+      ry=`echo 1.3.40 | sed -e 's/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*/\2/'`
+      rz=`echo 1.3.40 | sed -e 's/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*/\3/'`
+
+      version=`"$SWIG" -version | tr -d '\015'`
+
+      sx=`echo $version | sed -e 's/SWIG Version \([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*/\1/'`
+      sy=`echo $version | sed -e 's/SWIG Version \([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*/\2/'`
+      sz=`echo $version | sed -e 's/SWIG Version \([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*/\3/'`
+
+
+
+      if test $sx -gt $rx \
+         || (test $sx -eq $rx && test $sy -gt $ry) \
+         || (test $sx -eq $rx && test $sy -eq $ry && test $sz -ge $rz); then
+        { echo "$as_me:$LINENO: result: yes (found $sx.$sy.$sz)" >&5
+echo "${ECHO_T}yes (found $sx.$sy.$sz)" >&6; }
+
+
+        SWIGLIB=`"$SWIG" -swiglib`
+      else
+        { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+        { { echo "$as_me:$LINENO: error: Need SWIG version 1.3.40, but only found version $sx.$sy.$sz." >&5
+echo "$as_me: error: Need SWIG version 1.3.40, but only found version $sx.$sy.$sz." >&2;}
+   { (exit 1); exit 1; }; }
+      fi
+
+
+
+
+
+
 cat >>confdefs.h <<\_ACEOF
 #define USE_SWIG 1
 _ACEOF
@@ -22820,7 +22858,7 @@ _ACEOF
   fi
 
 
-  SWIGNEEDVERSION=1.3.39
+  SWIGNEEDVERSION=1.3.40
 
 
 
diff --git a/src/bindings/python/Makefile.in b/src/bindings/python/Makefile.in
--- a/src/bindings/python/Makefile.in
+++ b/src/bindings/python/Makefile.in
@@ -41,48 +41,28 @@ include @top_srcdir@/config/makefile-common-vars.mk
 srcdir  = @srcdir@
 thisdir = src/bindings/python
 
-# `sources' are used by the default rules to determine what needs to be
-# compiled.
+# In the normal core C++/C libSBML code, `sources' are used by the default
+# rules to determine what needs to be compiled.  In these language
+# bindings, the variable is not used by default rules, and everything is
+# handled explicitly below.  However, to maintain some resemblance to the
+# other libSBML build organization, we still use the name `sources'.
 
-sources = libsbml.py libsbml_wrap.cpp
+sources       = libsbml.py libsbml_wrap.cpp
+extra_sources = libsbml.i local.cpp local.i
 
-# What we're building is a module for use with Python.
-# The leading underscore below is a Python convention.
+# `libraries' is what we're building: a module for use with Python.
+# (The leading underscore in the name below is a Python convention.)
 
 libraries = _libsbml.$(PYTHON_EXT)
 
-#############################################################################
-#
-# Generates _libsbml.$(PYTHON_EXT) (C++ library for Python bindings) with
-# an object file in this directory (libsbml_wrap.o) and other object files
-# in sub directories in 'src' directory (src/sbml, src/common, ... ) instead
-# of linking a shared library of libSBML (libsbml.$(SHAREDLIBEXT)).
-#
+# The SWIG interface files should not need to be regenerated for recipients
+# of the libSBML distributions; only developers should need to regenerate
+# them.  The conditions for this are handled later below.
 
-#
-# All directories that contain *.{c,cpp} (implementation) files of libSBML need
-# to be listed in the following 'otherdirs' variable.
-#
-otherdirs = ../../common ../../util ../../xml ../../math ../../validator \
-            ../../validator/constraints ../../units ../../annotation ../../compress \
-            ../../sbml
+swig_sources = ../swig/libsbml.h ../swig/libsbml.i
 
 ifdef USE_LAYOUT
-  otherdirs += ../../sbml/layout
-endif
-
-objfiles  = libsbml_wrap.lo $(wildcard $(addsuffix /*.lo,$(otherdirs)))
-
-
-#############################################################################
-
-# Environment variable MACOSX_DEPLOYMENT_TARGET must be set to 10.3 or later
-# to use -undefined dynamic_lookup.
-
-ifeq "$(HOST_TYPE)" "darwin"
-  export MACOSX_DEPLOYMENT_TARGET=$(MACOS_VERSION)
-%.so: $(objfiles)
-	$(call link_dl_lib,$@)
+  swig_sources += ../swig/layout.i
 endif
 
 # If we're building 64-bit binaries, but are not running under 10.6, the 
@@ -112,7 +92,7 @@ extra_CPPFLAGS += $(PYTHON_CPPFLAGS) -I../swig -I../../../include
 SWIGFLAGS      += $(PYTHON_CPPFLAGS) -I../swig
 
 ifdef USE_LAYOUT
-  SWIGFLAGS += -DUSE_LAYOUT
+  SWIGFLAGS      += -DUSE_LAYOUT
   extra_CPPFLAGS += -DUSE_LAYOUT
 endif # USE_LAYOUT  
 
@@ -145,36 +125,29 @@ ifdef USE_LIBXML
   extra_LIBS     += @LIBXML_LIBS@
 endif
 
-# -fno-strict-aliasing option is added to CXXFLAGS when using GCC.
-# As written in the SWIG Manual (section 20.2.4), SWIG generated code could cause
-# crash problems when compiled by GCC with -fstrict-aliasing option (automatically
-# enabled when using -O2 or higher optimization in GCC 3 or later) and the option
-# should be disabled by adding -fno-strict-aliasing option.
+# -fno-strict-aliasing option is added to CXXFLAGS when using GCC.  As
+# written in the SWIG Manual (section 20.2.4), SWIG generated code could
+# cause crash problems when compiled by GCC with -fstrict-aliasing option
+# (automatically enabled when using -O2 or higher optimization in GCC 3 or
+# later) and the option should be disabled by adding -fno-strict-aliasing
+# option.
 
 ifeq (GCC,$(findstring GCC,$(shell $(CXX) --version)))
       CXXFLAGS += -fno-strict-aliasing
 endif
 
-# For Linux/Unix LD_LIBRARY_PATH *may* need to contain one or more library
-# paths to libsbml.so, libxerces-c.so and/or libexpat.so and/or the
-# libsbml.so _libsbml.so generated by this Makfile.  (For BSD/MacOS X
-# replace LD_LIBRARY_PATH with DYLD_LIBRARY_PATH.)
-
 # `distfiles' determines the files and directories included in a distribution.
 # `distfiles_exclude' is used to filter out specific items, so that even if
 # they appear in `distfiles', they will not be copied in the distribution.
 
-distfiles =                                     \
-            Makefile.in                         \
-            test.py                             \
-            layout_local.i                      \
-            libsbml.i                           \
-            libsbml.py                          \
-            libsbml_wrap.cpp                    \
-            local.cpp                           \
-            local.i                             \
-            setup.cfg                           \
-            setup.py.in                         \
+distfiles =                        \
+            Makefile.in            \
+            test.py                \
+            layout_local.i         \
+            setup.cfg              \
+            setup.py.in            \
+            $(sources)             \
+            $(extra_sources)       \
             $(python_test_files)
 
 python_test_path = test
@@ -183,17 +156,32 @@ python_test_files = $(wildcard $(python_test_path)/**/Test*.py)
 extra_clean     = build $(python_test_files:.py=.pyc) $(wildcard test.xml.*)
 extra_distclean = libsbml.pyc setup.py
 
-
-# -----------------------------------------------------------------------------
-# Primary build actions
-# -----------------------------------------------------------------------------
+# We generate _libsbml.$(PYTHON_EXT) (C++ library for Python bindings) with
+# an object file in this directory (libsbml_wrap.o) and other object files
+# in sub directories in 'src' directory (src/sbml, src/common, ... ) instead
+# of linking a shared library of libSBML (libsbml.$(SHAREDLIBEXT)).
 
-.SUFFIXES:
-.SUFFIXES: .i .cpp .py .pyc .pyo .o .obj .lo .la
+# All directories that contain *.{c,cpp} (implementation) files of libSBML need
+# to be listed in the following 'otherdirs' variable.
 
-# The default action is to remake everything.
+otherdirs = ../../common ../../util ../../xml ../../math ../../validator \
+            ../../validator/constraints ../../units ../../annotation ../../compress \
+            ../../sbml
 
-all: Makefile swig-prereq $(libraries)
+ifdef USE_LAYOUT
+  otherdirs += ../../sbml/layout
+endif
+
+objfiles  = libsbml_wrap.lo $(wildcard $(addsuffix /*.lo,$(otherdirs)))
+
+# Environment variable MACOSX_DEPLOYMENT_TARGET must be set to 10.3 or later
+# to use -undefined dynamic_lookup.
+
+ifeq "$(HOST_TYPE)" "darwin"
+  export MACOSX_DEPLOYMENT_TARGET=$(MACOS_VERSION)
+%.so: $(objfiles)
+	$(call link_dl_lib,$@)
+endif
 
 # The libSBML Python API library on MacOS X has to be built as a "bundle"
 # rather than a .dylib library.  This is different from the default rules
@@ -205,66 +193,70 @@ ifeq "$(HOST_TYPE)" "darwin"
   platform_link_flags = -bundle
 endif
 
-# The following is for developers and maintainers.  Recipients of the
-# library distributions shouldn't have to run SWIG because we provide the
-# wrapper file ready-made.  This is only enabled if configure is given the
-# --with-swig flag.
+# For Linux/Unix LD_LIBRARY_PATH *may* need to contain one or more library
+# paths to libsbml.so, libxerces-c.so and/or libexpat.so and/or the
+# libsbml.so _libsbml.so generated by this Makfile.  (For BSD/MacOS X
+# replace LD_LIBRARY_PATH with DYLD_LIBRARY_PATH.)
 
-swig_sources = \
-	  ../swig/libsbml.h \
-	  ../swig/libsbml.i
+
+# -----------------------------------------------------------------------------
+# Primary build actions
+# -----------------------------------------------------------------------------
 
-ifdef USE_LAYOUT
-  swig_sources += ../swig/layout.i
+.SUFFIXES:
+.SUFFIXES: .i .cpp .py .pyc .pyo .o .obj .lo .la
+
+# The default action is to remake everything.
+
+ifdef USE_PYTHON
+  all: Makefile libsbml.py libsbml_wrap.cpp $(libraries)
+else
+  all:
+	@echo
+	@echo "Reconfigure libSBML using --with-python to enable Python support.";
+	@echo
+	@exit 1
 endif
 
-ifdef USE_SWIG
-# If swig is enabled, always rebuild the swig wrapper files.
+setup.py: setup.py.in
+	cd $(TOP_BUILDDIR) && $(SHELL) ./config.status $(thisdir)/setup.py
 
-swig-prereq:
-	$(MAKE) swigfiles
+# Rummage through ../swig/libsbml.i to figure out the core libSBML files that
+# are our dependencies.
 
-else # not USE_SWIG
+main_sources = \
+  $(shell grep '%include sbml' ../swig/libsbml.i | grep -v 'libsbml-version.h' | cut -f2 -d' ' \
+    | cut -f2- -d'/' | sed -e '/\//s/^/..\/..\//;/\//!s/^/..\/..\/sbml\//')
 
 # If the last run was made with --enable-layout and this one isn't, or
 # vice-versa, the swig wrap files will be wrong for this run.  However, you
 # can't tell just by looking at file mod times, so you can't use normal
-# make dependencies.  So we do this grungy trick of looking at the file to
-# see what's inside.
+# make dependencies.  So we do this grungy trick of looking inside
+# libsbml_wrap.cpp to see what's inside.
 
-swig-prereq:
+.PHONY: do_reswig
+
 ifdef USE_LAYOUT
-	@if test -z "`grep SWIGTYPE_p_Layout libsbml_wrap.cpp`"; then \
-	  $(MAKE) swigfiles; \
-	else \
-	  $(MAKE) libsbml_wrap.cpp libsbml.py; \
-	fi
-else # not USE_LAYOUT
-	@if test -n "`grep SWIGTYPE_p_Layout libsbml_wrap.cpp`"; then \
-	  $(MAKE) swigfiles; \
-	else \
-	  $(MAKE) libsbml_wrap.cpp libsbml.py; \
-	fi
-endif # USE_LAYOUT
+  define check_layout
+    if test ! -f libsbml_wrap.cpp; then echo "do_reswig"; exit; fi; \
+    if test -z "`grep SWIGTYPE_p_Layout libsbml_wrap.cpp`"; then echo "do_reswig"; fi;
+  endef
+else
+  define check_layout
+    if test ! -f libsbml_wrap.cpp; then echo "do_reswig"; exit; fi; \
+    if test -n "`grep SWIGTYPE_p_Layout libsbml_wrap.cpp`"; then echo "do_reswig"; fi;
+  endef
+endif
 
-endif # USE_SWIG
+# Note: in SWIG 1.3.39, a compilation error can happen in SWIG-generated
+# code (libsbml_wrap.cpp) when using Python 3.x on 64-bit platforms.  To
+# avoid this, we add a cast (int* -> Py_ssize_t*) to the 3rd argument of
+# PyBytes_AsStringAndSize() function call in the file by using the sed
+# command in the following block.  (The SWIG problem is fixed in 1.3.40.)
 
-# The next target is for forcing re-swigging.
+libsbml.py: libsbml_wrap.cpp
 
-#
-# (NOTE: 2009-08-15) 
-#
-# In SWIG 1.3.39, a compilation error can happen in SWIG-generated code 
-# (libsbml_wrap.cpp) when built with Python 3.x on 64bit platform.
-# To avoid this problem, a cast code (int* -> Py_ssize_t*) is added
-# to the 3rd argument of PyBytes_AsStringAndSize() function call
-# in the file by using sed command in the following ifdef USE_SWIG
-# block.
-#
-# (2009-08-18: The above problem has been fixed in SWIG 1.3.40)
-#
-
-swigfiles:
+libsbml_wrap.cpp: $(swig_sources) $(main_sources) $(shell $(call check_layout))
 	@top_srcdir@/config/chk_swig_version.sh || exit
 	../swig/swigdoc.py python -I../.. -D../../../docs/src ../swig/libsbml.i pydoc.i
 	$(SWIG) $(SWIGFLAGS) \
@@ -280,14 +272,6 @@ swigfiles:
 	  libsbml_wrap.cpp.org > libsbml_wrap.cpp; \
 	fi 	
 
-# The following are the normal dependency rules.
-
-libsbml_wrap.cpp libsbml.py: $(swig_sources)
-	$(MAKE) swigfiles
-
-setup.py: setup.py.in
-	cd $(TOP_BUILDDIR) && $(SHELL) ./config.status $(thisdir)/setup.py
-
 
 # -----------------------------------------------------------------------------
 # Checking.
@@ -295,7 +279,7 @@ setup.py: setup.py.in
 
 test_subdir_path = test/sbml:test/xml:test/annotation:test/math
 ifdef USE_LIBCHECK
-  check: $(libraries)
+  check: $(libraries) $(shell $(call check_layout))
 	@echo
 	@echo
 	@echo Running Tests in $(thisdir)
