Added a code to check the existence of perl command and ExtUtils::MakeMaker module in "config/perl.m4".

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4585,6 +4585,21 @@ fi
 
     fi
 
+    if test $PERL != "perl" && ! test -f $PERL;
+    then
+      { { echo "$as_me:$LINENO: error: *** $PERL missing - please install first or check config.log ***" >&5
+echo "$as_me: error: *** $PERL missing - please install first or check config.log ***" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+
+    CHECK_MK=`($PERL -mExtUtils::MakeMaker -e '{print "OK"}') 2>/dev/null`
+    if test x$CHECK_MK != xOK;
+    then
+      { { echo "$as_me:$LINENO: error: *** ExtUtils::MakeMaker module is missing - please install first or check config.log ***" >&5
+echo "$as_me: error: *** ExtUtils::MakeMaker module is missing - please install first or check config.log ***" >&2;}
+   { (exit 1); exit 1; }; }
+    fi
+
 
 cat >>confdefs.h <<\_ACEOF
 #define USE_PERL 1
@@ -5734,7 +5749,7 @@ if test "${ac_cv_FUNC_LISPEXIT+set}" = set; then
 else
   ac_cv_FUNC_LISPEXIT=no-exit
     for ex in "sb-ext:quit :unix-status" "lisp:exit" "excl:exit" "sys:exit" "ext:quit" "unix:unix-exit" "no-exit" ; do
-      echo "configure:5737 trying $ex ..." >&5
+      echo "configure:5752 trying $ex ..." >&5
       echo "(ignore-errors ($ex 127))"|$LISP 2>&5 1>&5
       if test "$?" = "127" ; then
         ac_cv_FUNC_LISPEXIT=$ex
