Fixed configure related scripts.
 1) config/java.m4

    - Fixed the code which follows a symbolic link of JAVAC in order to 
      properly follow a symbolic link which points to a releative path 
     (e.g.  "/usr/bin/java -> ../java/bin/java" is used on OpenSolaris)

    - Fixed the code which checks Java's include directory in order to 
      not always fail due to missing ${headers} on non-MacOSX system.
      
 2) configure
    - Synched with the above update.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -709,7 +709,6 @@ JAR
 USE_JAVA
 JAVA_CPPFLAGS
 JAVA_LDFLAGS
-JAVA_LIBS
 JNIEXT
 JNIBASENAME
 JAVADOC_JAR
@@ -4744,7 +4743,6 @@ echo "$as_me: error: Need Java version 1.5.0, but only found version $jx.$jy.$jz
       fi
 
 
-      JAVA_VER_MAJOR=$jx
       JAVA_VER_MINOR=$jy
       JAVA_VER_SUBMINOR=$jz
 
@@ -4753,242 +4751,95 @@ echo "$as_me: error: Need Java version 1.5.0, but only found version $jx.$jy.$jz
 
 
 
-  test "x$JAVAC" = x && { { echo "$as_me:$LINENO: error: '$JAVAC' undefined" >&5
-echo "$as_me: error: '$JAVAC' undefined" >&2;}
-   { (exit 1); exit 1; }; }
-
-  JAVA_CPPFLAGS=
-  { echo "$as_me:$LINENO: checking for JAVA_HOME" >&5
-echo $ECHO_N "checking for JAVA_HOME... $ECHO_C" >&6; }
-
-    _cur=""$JAVAC""
-  while ls -ld "$_cur" 2>/dev/null | grep " -> " >/dev/null; do
-        _slink=`ls -ld "$_cur" | sed 's/.* -> //'`
-        case "$_slink" in
-          /*) _cur="$_slink";;
-                    *) _cur=`echo "X$_cur" | sed -e 's/^X//' -e 's:[^/]*$::'`"$_slink";;
-        esac
-        JAVA_FOLLOWED="$_cur"
-
-    _jtopdir=`echo "$JAVA_FOLLOWED" | sed -e 's://*:/:g' -e 's:/[^/]*$::'`
-    case "$host_os" in
-      *darwin*)
-        java_bail=no
-        java_mac_prefix="/System/Library/Frameworks/JavaVM.framework"
-        case $JAVA_VER_MINOR in
-          6)
-            if test -e "$java_mac_prefix/Versions/CurrentJDK/Headers"; then
-              _jinc="$java_mac_prefix/Versions/CurrentJDK/Headers"
-            elif test -e "$java_mac_prefix/Versions/1.6.0/Headers"; then
-              _jinc="$java_mac_prefix/Versions/1.6.0/Headers"
-            elif test -e "$java_mac_prefix/Versions/1.6/Headers"; then
-              _jinc="$java_mac_prefix/Versions/1.6/Headers"
-            else
-              java_bail=yes
-            fi
-            ;;
-          5)
-            if test -e "$java_mac_prefix/Versions/CurrentJDK/Headers"; then
-              _jinc="$java_mac_prefix/Versions/CurrentJDK/Headers"
-            elif test -e "$java_mac_prefix/Versions/1.5.0/Headers"; then
-              _jinc="$java_mac_prefix/Versions/1.5.0/Headers"
-            elif test -e "$java_mac_prefix/Versions/1.5/Headers"; then
-              _jinc="$java_mac_prefix/Versions/1.5/Headers"
-            else
-              java_bail=yes
-            fi
-            ;;
-          4)
-                                                                                                              if test $JAVA_VER_SUBMINOR -eq 2; then
-              if test -e "$java_mac_prefix/Versions/1.4.2/Headers"; then
-                _jinc="$java_mac_prefix/Versions/1.4.2/Headers"
-                elif test -e "$java_mac_prefix/Versions/1.4.1/Headers"; then
-                _jinc="$java_mac_prefix/Versions/1.4.1/Headers"
-                else
-                java_bail=yes
-              fi;
-            elif test $JAVA_VER_SUBMINOR -eq 1; then
-              if test -e "$java_mac_prefix/Versions/1.4.1/Headers"; then
-                _jinc="$java_mac_prefix/Versions/1.4.1/Headers"
-                else
-                java_bail=yes
-              fi;
-              else
-              java_bail=yes
-            fi
-            ;;
-          3)
-            if test -e "$java_mac_prefix/Versions/1.3.1/Headers"; then
-              _jinc="$java_mac_prefix/Versions/1.3.1/Headers"
-            elif test -e "$java_mac_prefix/Versions/1.3/Headers"; then
-              _jinc="$java_mac_prefix/Versions/1.3/Headers"
-            else
-              java_bail=yes
-            fi
-            ;;
-	  *)
-             _jtopdir=`echo "$_jtopdir" | sed -e 's:/[^/]*$::'`
-	     _jinc="$_jtopdir/Headers"
-	     ;;
-        esac
-
-	if test $java_bail = yes; then
-          { { echo "$as_me:$LINENO: error: Cannot find Java include files." >&5
-echo "$as_me: error: Cannot find Java include files." >&2;}
-   { (exit 1); exit 1; }; }
-          { { echo "$as_me:$LINENO: error: MacOS X 10.3.x has known problems with its Java 1.4 installation." >&5
-echo "$as_me: error: MacOS X 10.3.x has known problems with its Java 1.4 installation." >&2;}
-   { (exit 1); exit 1; }; }
-          { { echo "$as_me:$LINENO: error: See http://developer.apple.com/java/faq." >&5
-echo "$as_me: error: See http://developer.apple.com/java/faq." >&2;}
-   { (exit 1); exit 1; }; }
-	fi
-        _jlib=`echo "$_jinc" | sed -e 's:/[^/]*$:/Classes:'`
-        JAVADOC_JAR=$_jlib/classes.jar
-	;;
-    *)
-        _jtopdir=`echo "$_jtopdir" | sed -e 's:/[^/]*$::'`
-        _jinc="$_jtopdir/include"
-        JAVADOC_JAR=$_jtopdir/lib/tools.jar
-	;;
-    esac
-    if test -e "$_jinc/jni.h"; then
-      JAVA_CPPFLAGS="$JAVA_CPPFLAGS -I\"$_jinc\""
-    else
-      _jtopdir=`echo "$_jtopdir" | sed -e 's:/[^/]*$::'`
-      if test -e "$_jtopdir/include/jni.h"; then
-        JAVA_CPPFLAGS="$JAVA_CPPFLAGS -I\"$_jtopdir/include\""
-      fi
-    fi
-    if test -n "$JAVA_CPPFLAGS"; then
-      { echo "$as_me:$LINENO: result: $_jtopdir" >&5
-echo "${ECHO_T}$_jtopdir" >&6; }
-      break
-    fi
-
-  done
-  JAVA_FOLLOWED="$_cur"
-
-    _jtopdir=`echo "$JAVA_FOLLOWED" | sed -e 's://*:/:g' -e 's:/[^/]*$::'`
-    case "$host_os" in
-      *darwin*)
-        java_bail=no
-        java_mac_prefix="/System/Library/Frameworks/JavaVM.framework"
-        case $JAVA_VER_MINOR in
-          6)
-            if test -e "$java_mac_prefix/Versions/CurrentJDK/Headers"; then
-              _jinc="$java_mac_prefix/Versions/CurrentJDK/Headers"
-            elif test -e "$java_mac_prefix/Versions/1.6.0/Headers"; then
-              _jinc="$java_mac_prefix/Versions/1.6.0/Headers"
-            elif test -e "$java_mac_prefix/Versions/1.6/Headers"; then
-              _jinc="$java_mac_prefix/Versions/1.6/Headers"
-            else
-              java_bail=yes
-            fi
-            ;;
-          5)
-            if test -e "$java_mac_prefix/Versions/CurrentJDK/Headers"; then
-              _jinc="$java_mac_prefix/Versions/CurrentJDK/Headers"
-            elif test -e "$java_mac_prefix/Versions/1.5.0/Headers"; then
-              _jinc="$java_mac_prefix/Versions/1.5.0/Headers"
-            elif test -e "$java_mac_prefix/Versions/1.5/Headers"; then
-              _jinc="$java_mac_prefix/Versions/1.5/Headers"
-            else
-              java_bail=yes
-            fi
-            ;;
-          4)
-                                                                                                              if test $JAVA_VER_SUBMINOR -eq 2; then
-              if test -e "$java_mac_prefix/Versions/1.4.2/Headers"; then
-                _jinc="$java_mac_prefix/Versions/1.4.2/Headers"
-                elif test -e "$java_mac_prefix/Versions/1.4.1/Headers"; then
-                _jinc="$java_mac_prefix/Versions/1.4.1/Headers"
-                else
-                java_bail=yes
-              fi;
-            elif test $JAVA_VER_SUBMINOR -eq 1; then
-              if test -e "$java_mac_prefix/Versions/1.4.1/Headers"; then
-                _jinc="$java_mac_prefix/Versions/1.4.1/Headers"
-                else
-                java_bail=yes
-              fi;
-              else
-              java_bail=yes
-            fi
-            ;;
-          3)
-            if test -e "$java_mac_prefix/Versions/1.3.1/Headers"; then
-              _jinc="$java_mac_prefix/Versions/1.3.1/Headers"
-            elif test -e "$java_mac_prefix/Versions/1.3/Headers"; then
-              _jinc="$java_mac_prefix/Versions/1.3/Headers"
-            else
-              java_bail=yes
-            fi
-            ;;
-	  *)
-             _jtopdir=`echo "$_jtopdir" | sed -e 's:/[^/]*$::'`
-	     _jinc="$_jtopdir/Headers"
-	     ;;
-        esac
-
-	if test $java_bail = yes; then
-          { { echo "$as_me:$LINENO: error: Cannot find Java include files." >&5
-echo "$as_me: error: Cannot find Java include files." >&2;}
-   { (exit 1); exit 1; }; }
-          { { echo "$as_me:$LINENO: error: MacOS X 10.3.x has known problems with its Java 1.4 installation." >&5
-echo "$as_me: error: MacOS X 10.3.x has known problems with its Java 1.4 installation." >&2;}
-   { (exit 1); exit 1; }; }
-          { { echo "$as_me:$LINENO: error: See http://developer.apple.com/java/faq." >&5
-echo "$as_me: error: See http://developer.apple.com/java/faq." >&2;}
-   { (exit 1); exit 1; }; }
-	fi
-        _jlib=`echo "$_jinc" | sed -e 's:/[^/]*$:/Classes:'`
-        JAVADOC_JAR=$_jlib/classes.jar
-	;;
-    *)
-        _jtopdir=`echo "$_jtopdir" | sed -e 's:/[^/]*$::'`
-        _jinc="$_jtopdir/include"
-        JAVADOC_JAR=$_jtopdir/lib/tools.jar
-	;;
-    esac
-    if test -e "$_jinc/jni.h"; then
-      JAVA_CPPFLAGS="$JAVA_CPPFLAGS -I\"$_jinc\""
-    else
-      _jtopdir=`echo "$_jtopdir" | sed -e 's:/[^/]*$::'`
-      if test -e "$_jtopdir/include/jni.h"; then
-        JAVA_CPPFLAGS="$JAVA_CPPFLAGS -I\"$_jtopdir/include\""
-      fi
-    fi
-    if test -n "$JAVA_CPPFLAGS"; then
-      { echo "$as_me:$LINENO: result: $_jtopdir" >&5
-echo "${ECHO_T}$_jtopdir" >&6; }
-      break
-    fi
-
-
-
-  if test -z "$JAVA_CPPFLAGS"; then
-    { { echo "$as_me:$LINENO: error: Cannot find Java include fiiles. " >&5
-echo "$as_me: error: Cannot find Java include fiiles. " >&2;}
-   { (exit 1); exit 1; }; }
-  else
-        case "$host_os" in
-      freebsd*) _java_inc_subdirs="freebsd";;
-      bsdi*)    _java_inc_subdirs="bsdos";;
-      linux*)   _java_inc_subdirs="linux genunix";;
-      osf*)     _java_inc_subdirs="alpha";;
-      solaris*) _java_inc_subdirs="solaris";;
-      *cygwin*) _java_inc_subdirs="win32";;
-      *)        _java_inc_subdirs="genunix";;
-    esac
-
-        for jsubdir in $_java_inc_subdirs; do
-      if test -d "$_jtopdir/include/$jsubdir"; then
-        JAVA_CPPFLAGS="$JAVA_CPPFLAGS -I\"$_jtopdir/include/$jsubdir\""
-      fi
+    while test -h "$JAVAC"; do
+      _slink=`readlink "$JAVAC"`
+                              case "$_slink" in
+        /*) JAVAC="$_slink";;
+                  *) JAVAC=`echo "X${JAVAC}" | sed -e 's/^X//' -e 's:[^/]*$::'`"$_slink";;
+      esac
     done
-  fi
 
+
+    case "$host" in
+      *darwin*)
+        framework="/System/Library/Frameworks/JavaVM.framework"
+        case $JAVA_VER_MINOR in
+          6)
+            if test -e "$framework/Versions/CurrentJDK/Headers"; then
+              headers="$framework/Versions/CurrentJDK/Headers"
+            elif test -e "$framework/Versions/1.6.0/Headers"; then
+              headers="$framework/Versions/1.6.0/Headers"
+            elif test -e "$framework/Versions/1.6/Headers"; then
+              headers="$framework/Versions/1.6/Headers"
+            fi
+            ;;
+          5)
+            if test -e "$framework/Versions/CurrentJDK/Headers"; then
+              headers="$framework/Versions/CurrentJDK/Headers"
+            elif test -e "$framework/Versions/1.5.0/Headers"; then
+              headers="$framework/Versions/1.5.0/Headers"
+            elif test -e "$framework/Versions/1.5/Headers"; then
+              headers="$framework/Versions/1.5/Headers"
+            fi
+            ;;
+          4)
+                                                                                                if test $JAVA_VER_SUBMINOR -eq 2; then
+              if test -e "$framework/Versions/1.4.2/Headers"; then
+                headers="$framework/Versions/1.4.2/Headers"
+                elif test -e "$framework/Versions/1.4.1/Headers"; then
+                headers="$framework/Versions/1.4.1/Headers"
+              fi;
+            elif test $JAVA_VER_SUBMINOR -eq 1; then
+              if test -e "$framework/Versions/1.4.1/Headers"; then
+                headers="$framework/Versions/1.4.1/Headers"
+              fi;
+            fi
+            ;;
+        esac
+
+        if test -e "$headers/jni.h"; then
+          JAVA_CPPFLAGS="$JAVA_CPPFLAGS -I\"$headers\""
+          parent=`dirname "$headers"`
+          JAVADOC_JAR="$parent/Classes/classes.jar"
+        else
+          { { echo "$as_me:$LINENO: error: Cannot find Java include files." >&5
+echo "$as_me: error: Cannot find Java include files." >&2;}
+   { (exit 1); exit 1; }; }
+        fi
+      ;;
+
+      *)
+        parent=`dirname "$JAVAC"`
+
+        if test -e "$parent/include/jni.h"; then
+          headers="${parent}/include"
+          JAVA_CPPFLAGS="$JAVA_CPPFLAGS -I\"${headers}\""
+        else
+
+
+          parent=`dirname "${parent}"`
+
+          if test -e "${parent}/include/jni.h"; then
+            headers="${parent}/include"
+            JAVA_CPPFLAGS="$JAVA_CPPFLAGS -I\"${headers}\""
+          else
+            { { echo "$as_me:$LINENO: error: Cannot find Java include files." >&5
+echo "$as_me: error: Cannot find Java include files." >&2;}
+   { (exit 1); exit 1; }; }
+          fi
+        fi
+
+
+        case "$host_os" in
+          *cygwin*) JAVA_CPPFLAGS="$JAVA_CPPFLAGS -I\"$parent/include/win32\"";;
+          freebsd*) JAVA_CPPFLAGS="$JAVA_CPPFLAGS -I\"$parent/include/freebsd\"";;
+          linux*)   JAVA_CPPFLAGS="$JAVA_CPPFLAGS -I\"$parent/include/linux\"";;
+          solaris*) JAVA_CPPFLAGS="$JAVA_CPPFLAGS -I\"$parent/include/solaris\"";;
+        esac
+
+        JAVADOC_JAR="$parent/lib/tools.jar"
+      ;;
+    esac
 
 
     case $host in
@@ -5016,8 +4867,11 @@ echo "$as_me: error: Cannot find Java include fiiles. " >&2;}
 	;;
     esac
 
-
-    JAVA_LIBS=
+    if test -z "$headers"; then
+      { { echo "$as_me:$LINENO: error: Cannot find Java include files." >&5
+echo "$as_me: error: Cannot find Java include files." >&2;}
+   { (exit 1); exit 1; }; }
+    fi
 
 
 cat >>confdefs.h <<\_ACEOF
@@ -5025,7 +4879,6 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
     USE_JAVA=1
-
 
 
 
@@ -6687,12 +6540,13 @@ else
 fi
 
 
-  if test "$with_doxygen" != "yes" && test "$with_doxygen" != "no"; then
+  if test "$with_doxygen" != "no"; then
+    if test "$with_doxygen" != "yes"; then
 
 
-    with_doxygen=`echo $with_doxygen | sed -e 's,\(.*\)/$,\1,g'`
+      with_doxygen=`echo $with_doxygen | sed -e 's,\(.*\)/$,\1,g'`
 
-    # Extract the first word of "doxygen", so it can be a program name with args.
+      # Extract the first word of "doxygen", so it can be a program name with args.
 set dummy doxygen; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
@@ -6733,8 +6587,8 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
-  else
-        # Extract the first word of "doxygen", so it can be a program name with args.
+    else
+            # Extract the first word of "doxygen", so it can be a program name with args.
 set dummy doxygen; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
@@ -6774,6 +6628,7 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
+    fi
   fi
 
   if test -n "$DOXYGEN"; then
@@ -6821,7 +6676,7 @@ _ACEOF
 
 
 
-    if test $with_java; then
+    if test "$with_java" != "no"; then
       { echo "$as_me:$LINENO: checking for javadoc" >&5
 echo $ECHO_N "checking for javadoc... $ECHO_C" >&6; }
       if ! test -e $JAVADOC_JAR; then
@@ -12215,10 +12070,10 @@ JAR!$JAR$ac_delim
 USE_JAVA!$USE_JAVA$ac_delim
 JAVA_CPPFLAGS!$JAVA_CPPFLAGS$ac_delim
 JAVA_LDFLAGS!$JAVA_LDFLAGS$ac_delim
-JAVA_LIBS!$JAVA_LIBS$ac_delim
 JNIEXT!$JNIEXT$ac_delim
 JNIBASENAME!$JNIBASENAME$ac_delim
 JAVADOC_JAR!$JAVADOC_JAR$ac_delim
+MEX!$MEX$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -12260,7 +12115,6 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
-MEX!$MEX$ac_delim
 MATLAB!$MATLAB$ac_delim
 USE_MATLAB!$USE_MATLAB$ac_delim
 MATLAB_CPPFLAGS!$MATLAB_CPPFLAGS$ac_delim
@@ -12327,7 +12181,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 65; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 64; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
