Improved the autoconf macro for java (config/java.m4) to avoid a configure error which could happen on some platforms.
The change is based on a patch provided by Moriyoshi Koizumi.
Thanks to Moriyoshi for providing the patch.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4939,11 +4939,13 @@ echo "$as_me: error: Need Java version 1.4.0 but only found version $version." >
 
 
 
-
   test "x$JAVAC" = x && { { echo "$as_me:$LINENO: error: '$JAVAC' undefined" >&5
 echo "$as_me: error: '$JAVAC' undefined" >&2;}
    { (exit 1); exit 1; }; }
 
+  JAVA_CPPFLAGS=
+  { echo "$as_me:$LINENO: checking for JAVA_HOME" >&5
+echo $ECHO_N "checking for JAVA_HOME... $ECHO_C" >&6; }
 
     _cur=""$JAVAC""
   while ls -ld "$_cur" 2>/dev/null | grep " -> " >/dev/null; do
@@ -4952,70 +4954,69 @@ echo "$as_me: error: '$JAVAC' undefined" >&2;}
           /*) _cur="$_slink";;
                     *) _cur=`echo "X$_cur" | sed -e 's/^X//' -e 's:[^/]*$::'`"$_slink";;
         esac
-  done
-  JAVA_FOLLOWED="$_cur"
+        JAVA_FOLLOWED="$_cur"
 
-  _jtopdir=`echo "$JAVA_FOLLOWED" | sed -e 's://*:/:g' -e 's:/[^/]*$::'`
-  case "$host_os" in
-    *darwin*)
-	java_bail=no
-	java_mac_prefix="/System/Library/Frameworks/JavaVM.framework"
-	case $JAVA_VER_MINOR in
-	  6)
-	    if test -e "$java_mac_prefix/Versions/CurrentJDK/Headers"; then
-	      _jinc="$java_mac_prefix/Versions/CurrentJDK/Headers"
-	    elif test -e "$java_mac_prefix/Versions/1.6.0/Headers"; then
-	      _jinc="$java_mac_prefix/Versions/1.6.0/Headers"
-	    elif test -e "$java_mac_prefix/Versions/1.6/Headers"; then
-	      _jinc="$java_mac_prefix/Versions/1.6/Headers"
-	    else
-	      java_bail=yes
-	    fi
-	    ;;
-	  5)
-	    if test -e "$java_mac_prefix/Versions/CurrentJDK/Headers"; then
-	      _jinc="$java_mac_prefix/Versions/CurrentJDK/Headers"
-	    elif test -e "$java_mac_prefix/Versions/1.5.0/Headers"; then
-	      _jinc="$java_mac_prefix/Versions/1.5.0/Headers"
-	    elif test -e "$java_mac_prefix/Versions/1.5/Headers"; then
-	      _jinc="$java_mac_prefix/Versions/1.5/Headers"
-	    else
-	      java_bail=yes
-	    fi
-	    ;;
-	  4)
-                                                                                    	    if test $JAVA_VER_SUBMINOR -eq 2; then
-	      if test -e "$java_mac_prefix/Versions/1.4.2/Headers"; then
-	        _jinc="$java_mac_prefix/Versions/1.4.2/Headers"
-              elif test -e "$java_mac_prefix/Versions/1.4.1/Headers"; then
-	        _jinc="$java_mac_prefix/Versions/1.4.1/Headers"
-              else
-	        java_bail=yes
-	      fi;
-	    elif test $JAVA_VER_SUBMINOR -eq 1; then
-	      if test -e "$java_mac_prefix/Versions/1.4.1/Headers"; then
-	        _jinc="$java_mac_prefix/Versions/1.4.1/Headers"
-              else
-	        java_bail=yes
-	      fi;
+    _jtopdir=`echo "$JAVA_FOLLOWED" | sed -e 's://*:/:g' -e 's:/[^/]*$::'`
+    case "$host_os" in
+      *darwin*)
+        java_bail=no
+        java_mac_prefix="/System/Library/Frameworks/JavaVM.framework"
+        case $JAVA_VER_MINOR in
+          6)
+            if test -e "$java_mac_prefix/Versions/CurrentJDK/Headers"; then
+              _jinc="$java_mac_prefix/Versions/CurrentJDK/Headers"
+            elif test -e "$java_mac_prefix/Versions/1.6.0/Headers"; then
+              _jinc="$java_mac_prefix/Versions/1.6.0/Headers"
+            elif test -e "$java_mac_prefix/Versions/1.6/Headers"; then
+              _jinc="$java_mac_prefix/Versions/1.6/Headers"
             else
-	      java_bail=yes
-	    fi
-	    ;;
-	  3)
-	    if test -e "$java_mac_prefix/Versions/1.3.1/Headers"; then
-	      _jinc="$java_mac_prefix/Versions/1.3.1/Headers"
-	    elif test -e "$java_mac_prefix/Versions/1.3/Headers"; then
-	      _jinc="$java_mac_prefix/Versions/1.3/Headers"
-	    else
-	      java_bail=yes
-	    fi
-	    ;;
+              java_bail=yes
+            fi
+            ;;
+          5)
+            if test -e "$java_mac_prefix/Versions/CurrentJDK/Headers"; then
+              _jinc="$java_mac_prefix/Versions/CurrentJDK/Headers"
+            elif test -e "$java_mac_prefix/Versions/1.5.0/Headers"; then
+              _jinc="$java_mac_prefix/Versions/1.5.0/Headers"
+            elif test -e "$java_mac_prefix/Versions/1.5/Headers"; then
+              _jinc="$java_mac_prefix/Versions/1.5/Headers"
+            else
+              java_bail=yes
+            fi
+            ;;
+          4)
+                                                                                                              if test $JAVA_VER_SUBMINOR -eq 2; then
+              if test -e "$java_mac_prefix/Versions/1.4.2/Headers"; then
+                _jinc="$java_mac_prefix/Versions/1.4.2/Headers"
+                elif test -e "$java_mac_prefix/Versions/1.4.1/Headers"; then
+                _jinc="$java_mac_prefix/Versions/1.4.1/Headers"
+                else
+                java_bail=yes
+              fi;
+            elif test $JAVA_VER_SUBMINOR -eq 1; then
+              if test -e "$java_mac_prefix/Versions/1.4.1/Headers"; then
+                _jinc="$java_mac_prefix/Versions/1.4.1/Headers"
+                else
+                java_bail=yes
+              fi;
+              else
+              java_bail=yes
+            fi
+            ;;
+          3)
+            if test -e "$java_mac_prefix/Versions/1.3.1/Headers"; then
+              _jinc="$java_mac_prefix/Versions/1.3.1/Headers"
+            elif test -e "$java_mac_prefix/Versions/1.3/Headers"; then
+              _jinc="$java_mac_prefix/Versions/1.3/Headers"
+            else
+              java_bail=yes
+            fi
+            ;;
 	  *)
              _jtopdir=`echo "$_jtopdir" | sed -e 's:/[^/]*$::'`
 	     _jinc="$_jtopdir/Headers"
 	     ;;
-	esac
+        esac
 
 	if test $java_bail = yes; then
           { { echo "$as_me:$LINENO: error: Cannot find Java include files." >&5
@@ -5036,34 +5037,142 @@ echo "$as_me: error: See http://developer.apple.com/java/faq." >&2;}
         _jinc="$_jtopdir/include"
         JAVADOC_JAR=$_jtopdir/lib/tools.jar
 	;;
-  esac
-  if test -e "$_jinc/jni.h"; then
-    JAVA_CPPFLAGS="$JAVA_CPPFLAGS -I\"$_jinc\""
-  else
-    _jtopdir=`echo "$_jtopdir" | sed -e 's:/[^/]*$::'`
-    if test -e "$_jtopdir/include/jni.h"; then
-      JAVA_CPPFLAGS="$JAVA_CPPFLAGS -I\"$_jtopdir/include\""
+    esac
+    if test -e "$_jinc/jni.h"; then
+      JAVA_CPPFLAGS="$JAVA_CPPFLAGS -I\"$_jinc\""
     else
-      { { echo "$as_me:$LINENO: error: Cannot find Java include files." >&5
+      _jtopdir=`echo "$_jtopdir" | sed -e 's:/[^/]*$::'`
+      if test -e "$_jtopdir/include/jni.h"; then
+        JAVA_CPPFLAGS="$JAVA_CPPFLAGS -I\"$_jtopdir/include\""
+      fi
+    fi
+    if test -n "$JAVA_CPPFLAGS"; then
+      { echo "$as_me:$LINENO: result: $_jtopdir" >&5
+echo "${ECHO_T}$_jtopdir" >&6; }
+      break
+    fi
+
+  done
+  JAVA_FOLLOWED="$_cur"
+
+    _jtopdir=`echo "$JAVA_FOLLOWED" | sed -e 's://*:/:g' -e 's:/[^/]*$::'`
+    case "$host_os" in
+      *darwin*)
+        java_bail=no
+        java_mac_prefix="/System/Library/Frameworks/JavaVM.framework"
+        case $JAVA_VER_MINOR in
+          6)
+            if test -e "$java_mac_prefix/Versions/CurrentJDK/Headers"; then
+              _jinc="$java_mac_prefix/Versions/CurrentJDK/Headers"
+            elif test -e "$java_mac_prefix/Versions/1.6.0/Headers"; then
+              _jinc="$java_mac_prefix/Versions/1.6.0/Headers"
+            elif test -e "$java_mac_prefix/Versions/1.6/Headers"; then
+              _jinc="$java_mac_prefix/Versions/1.6/Headers"
+            else
+              java_bail=yes
+            fi
+            ;;
+          5)
+            if test -e "$java_mac_prefix/Versions/CurrentJDK/Headers"; then
+              _jinc="$java_mac_prefix/Versions/CurrentJDK/Headers"
+            elif test -e "$java_mac_prefix/Versions/1.5.0/Headers"; then
+              _jinc="$java_mac_prefix/Versions/1.5.0/Headers"
+            elif test -e "$java_mac_prefix/Versions/1.5/Headers"; then
+              _jinc="$java_mac_prefix/Versions/1.5/Headers"
+            else
+              java_bail=yes
+            fi
+            ;;
+          4)
+                                                                                                              if test $JAVA_VER_SUBMINOR -eq 2; then
+              if test -e "$java_mac_prefix/Versions/1.4.2/Headers"; then
+                _jinc="$java_mac_prefix/Versions/1.4.2/Headers"
+                elif test -e "$java_mac_prefix/Versions/1.4.1/Headers"; then
+                _jinc="$java_mac_prefix/Versions/1.4.1/Headers"
+                else
+                java_bail=yes
+              fi;
+            elif test $JAVA_VER_SUBMINOR -eq 1; then
+              if test -e "$java_mac_prefix/Versions/1.4.1/Headers"; then
+                _jinc="$java_mac_prefix/Versions/1.4.1/Headers"
+                else
+                java_bail=yes
+              fi;
+              else
+              java_bail=yes
+            fi
+            ;;
+          3)
+            if test -e "$java_mac_prefix/Versions/1.3.1/Headers"; then
+              _jinc="$java_mac_prefix/Versions/1.3.1/Headers"
+            elif test -e "$java_mac_prefix/Versions/1.3/Headers"; then
+              _jinc="$java_mac_prefix/Versions/1.3/Headers"
+            else
+              java_bail=yes
+            fi
+            ;;
+	  *)
+             _jtopdir=`echo "$_jtopdir" | sed -e 's:/[^/]*$::'`
+	     _jinc="$_jtopdir/Headers"
+	     ;;
+        esac
+
+	if test $java_bail = yes; then
+          { { echo "$as_me:$LINENO: error: Cannot find Java include files." >&5
 echo "$as_me: error: Cannot find Java include files." >&2;}
    { (exit 1); exit 1; }; }
+          { { echo "$as_me:$LINENO: error: MacOS X 10.3.x has known problems with its Java 1.4 installation." >&5
+echo "$as_me: error: MacOS X 10.3.x has known problems with its Java 1.4 installation." >&2;}
+   { (exit 1); exit 1; }; }
+          { { echo "$as_me:$LINENO: error: See http://developer.apple.com/java/faq." >&5
+echo "$as_me: error: See http://developer.apple.com/java/faq." >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+        _jlib=`echo "$_jinc" | sed -e 's:/[^/]*$:/Classes:'`
+        JAVADOC_JAR=$_jlib/classes.jar
+	;;
+    *)
+        _jtopdir=`echo "$_jtopdir" | sed -e 's:/[^/]*$::'`
+        _jinc="$_jtopdir/include"
+        JAVADOC_JAR=$_jtopdir/lib/tools.jar
+	;;
+    esac
+    if test -e "$_jinc/jni.h"; then
+      JAVA_CPPFLAGS="$JAVA_CPPFLAGS -I\"$_jinc\""
+    else
+      _jtopdir=`echo "$_jtopdir" | sed -e 's:/[^/]*$::'`
+      if test -e "$_jtopdir/include/jni.h"; then
+        JAVA_CPPFLAGS="$JAVA_CPPFLAGS -I\"$_jtopdir/include\""
+      fi
     fi
+    if test -n "$JAVA_CPPFLAGS"; then
+      { echo "$as_me:$LINENO: result: $_jtopdir" >&5
+echo "${ECHO_T}$_jtopdir" >&6; }
+      break
+    fi
+
+
+
+  if test -z "$JAVA_CPPFLAGS"; then
+    { { echo "$as_me:$LINENO: error: Cannot find Java include fiiles. " >&5
+echo "$as_me: error: Cannot find Java include fiiles. " >&2;}
+   { (exit 1); exit 1; }; }
+  else
+        case "$host_os" in
+      bsdi*)    _java_inc_subdirs="bsdos";;
+      linux*)   _java_inc_subdirs="linux genunix";;
+      osf*)     _java_inc_subdirs="alpha";;
+      solaris*) _java_inc_subdirs="solaris";;
+      *cygwin*) _java_inc_subdirs="win32";;
+      *)        _java_inc_subdirs="genunix";;
+    esac
+
+        for jsubdir in $_java_inc_subdirs; do
+      if test -d "$_jtopdir/include/$jsubdir"; then
+        JAVA_CPPFLAGS="$JAVA_CPPFLAGS -I\"$_jtopdir/include/$jsubdir\""
+      fi
+    done
   fi
-
-    case "$host_os" in
-    bsdi*)    _java_inc_subdirs="bsdos";;
-    linux*)   _java_inc_subdirs="linux genunix";;
-    osf*)     _java_inc_subdirs="alpha";;
-    solaris*) _java_inc_subdirs="solaris";;
-    *cygwin*) _java_inc_subdirs="win32";;
-    *)        _java_inc_subdirs="genunix";;
-  esac
-
-    for jsubdir in $_java_inc_subdirs; do
-    if test -d "$_jtopdir/include/$jsubdir"; then
-      JAVA_CPPFLAGS="$JAVA_CPPFLAGS -I\"$_jtopdir/include/$jsubdir\""
-    fi
-  done
 
 
 
@@ -5765,7 +5874,7 @@ if test "${ac_cv_FUNC_LISPEXIT+set}" = set; then
 else
   ac_cv_FUNC_LISPEXIT=no-exit
     for ex in "sb-ext:quit :unix-status" "lisp:exit" "excl:exit" "sys:exit" "ext:quit" "unix:unix-exit" "no-exit" ; do
-      echo "configure:5768 trying $ex ..." >&5
+      echo "configure:5877 trying $ex ..." >&5
       echo "(ignore-errors ($ex 127))"|$LISP 2>&5 1>&5
       if test "$?" = "127" ; then
         ac_cv_FUNC_LISPEXIT=$ex
