1. Fixed nonportable code in which a path to a jar file for javadoc was hardcoded and    only valid for MacOSX (the path needs to be specified by -cp option in javac command    to build doc/src/ExcludeDoclet.java which is used to generate libSBML Java documentation).    Now, the ExcludeDoclet class can be properly built and invoked on MacOSX and non-MacOSX    platforms. 2. Fixed a typo in doc/src/Makefile.in.
Thanks to Moriyoshi Koizumi for pointing out these problems and providing a
patch.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -696,6 +696,7 @@ JAVA_LDFLAGS
 JAVA_LIBS
 JNIEXT
 JNIBASENAME
+JAVADOC_JAR
 MEX
 MATLAB
 USE_MATLAB
@@ -5002,7 +5003,7 @@ echo "$as_me: error: '$JAVAC' undefined" >&2;}
 	    ;;
 	  *)
              _jtopdir=`echo "$_jtopdir" | sed -e 's:/[^/]*$::'`
-	     _jinc="$_jtopdir/Versions/Current/Headers"
+	     _jinc="$_jtopdir/Versions/CurrentJDK/Headers"
 	     ;;
 	esac
 
@@ -5017,9 +5018,15 @@ echo "$as_me: error: MacOS X 10.3.x has known problems with its Java 1.4 install
 echo "$as_me: error: See http://developer.apple.com/java/faq." >&2;}
    { (exit 1); exit 1; }; }
 	fi
+        _jlib=`echo "$_jinc" | sed -e 's:/[^/]*$:/Classes:'`
+        JAVADOC_JAR=$_jlib/classes.jar
 	;;
     *)
+        if ! test -e "$_jtopdir/include"; then
+          _jtopdir=`echo "$_jtopdir" | sed -e 's:/[^/]*$::'`
+        fi
         _jinc="$_jtopdir/include"
+        JAVADOC_JAR=$_jtopdir/lib/tools.jar
 	;;
   esac
   if test -e "$_jinc/jni.h"; then
@@ -5086,6 +5093,7 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
     USE_JAVA=1
+
 
 
 
@@ -5749,7 +5757,7 @@ if test "${ac_cv_FUNC_LISPEXIT+set}" = set; then
 else
   ac_cv_FUNC_LISPEXIT=no-exit
     for ex in "sb-ext:quit :unix-status" "lisp:exit" "excl:exit" "sys:exit" "ext:quit" "unix:unix-exit" "no-exit" ; do
-      echo "configure:5752 trying $ex ..." >&5
+      echo "configure:5760 trying $ex ..." >&5
       echo "(ignore-errors ($ex 127))"|$LISP 2>&5 1>&5
       if test "$?" = "127" ; then
         ac_cv_FUNC_LISPEXIT=$ex
@@ -7111,6 +7119,23 @@ _ACEOF
       USE_DOXYGEN=1
 
     fi
+
+
+    if test $with_java; then
+      { echo "$as_me:$LINENO: checking for javadoc" >&5
+echo $ECHO_N "checking for javadoc... $ECHO_C" >&6; }
+      if ! test -e $JAVADOC_JAR; then
+        { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+        { { echo "$as_me:$LINENO: error: *** missing $JAVADOC_JAR - please install first or check config.log ***" >&5
+echo "$as_me: error: *** missing $JAVADOC_JAR - please install first or check config.log ***" >&2;}
+   { (exit 1); exit 1; }; }
+      else
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+      fi
+    fi
+
   fi
 
 
@@ -12972,8 +12997,8 @@ JAVA_LDFLAGS!$JAVA_LDFLAGS$ac_delim
 JAVA_LIBS!$JAVA_LIBS$ac_delim
 JNIEXT!$JNIEXT$ac_delim
 JNIBASENAME!$JNIBASENAME$ac_delim
+JAVADOC_JAR!$JAVADOC_JAR$ac_delim
 MEX!$MEX$ac_delim
-MATLAB!$MATLAB$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -13015,6 +13040,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+MATLAB!$MATLAB$ac_delim
 USE_MATLAB!$USE_MATLAB$ac_delim
 MATLAB_CPPFLAGS!$MATLAB_CPPFLAGS$ac_delim
 MATLAB_LDFLAGS!$MATLAB_LDFLAGS$ac_delim
@@ -13086,7 +13112,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 69; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 70; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
