Rewrote the makefile to be a little bit more careful about whether java has been configured and to detect whether Java 1.5 is in use.

diff --git a/examples/java/Makefile.in b/examples/java/Makefile.in
--- a/examples/java/Makefile.in
+++ b/examples/java/Makefile.in
@@ -1,11 +1,13 @@
+## @configure_input@
 ##
-## \file    Makefile.in
-## \brief   Makefile template for libsbml Java examples
-## \author  Mike Hucka
+## Filename    : Makefile
+## Description : Builds the Java example programs
+## Author(s)   : SBML Team <sbml-team@caltech.edu>
+## Created     : sometime in 2005
+## Revision    : $Id$
+## Source      : $Source$
 ##
-
-##
-## Copyright 2004 California Institute of Technology and
+## Copyright 2005 California Institute of Technology and
 ## Japan Science and Technology Corporation.
 ##
 ## This library is free software; you can redistribute it and/or modify it
@@ -34,61 +36,70 @@
 ##
 ## The original code contained here was initially developed by:
 ##
-##     Ben Bornstein and Ben Kovitz
-##     SBML Team
-##     Control and Dynamical Systems, MC 107-81
-##     California Institute of Technology
-##     Pasadena, CA, 91125, USA
+##     Nicolas Rodriguez
+##     EMBL Outstation -- Hinxton
+##     European Bioinformatics Institute
+##     Wellcome Trust Genome Campus, Hinxton
+##     Cambridge, CB10 1SD
+##     United Kingdom  
+##     http://www.ebi.ac.uk/compneur/
 ##
-##     http://www.sbml.org
-##     mailto:sbml-team@caltech.edu
-##
-## Contributor(s):
-##   Michael Hucka <mhucka@caltech.edu> Wrote this Makefile.in.
+## Contributions:
+## 2005-09-30 <mhucka@caltech.edu> Rewrote this Makefile.in
 ##
 
+# The values of the following variables are obtained using the libSBML
+# configuration program.
 
 CLASSPATH = ../../src/bindings/java/libsbmlj.jar:.
 
-JAVA   = @JAVA@
-JAVAC  = @JAVAC@
-JFLAGS = -classpath $(CLASSPATH)
+JAVA      = @JAVA@
+JAVAC     = @JAVAC@
+JFLAGS    = -classpath $(CLASSPATH)
 
-classes = convertSBML.class printMath.class printSBML.class readSBML.class \
+# The rest of this Makefile remains static regardless of the values
+# assigned to the variables above.
+
+classes   = convertSBML.class printMath.class printSBML.class readSBML.class \
           translateMath.class validateSBML.class evaluateMath.class
-
 
 all: $(classes)
 
-convertSBML.class: convertSBML.java libSBMLHelper.java
+# The following is the generic rule for making a .class file from one of
+# the .java files in this directory.  The funny business with evaluateMath
+# is because we have to use a special rule later below that takes into
+# account the fact that evaluateMath needs Java version 1.5 or higher.
+
+$(filter-out evaluateMath.class,$(classes)): %.class: %.java libSBMLHelper.java
+ifeq "@JAVA@" ""
+	@echo "libSBML must be configured with --with-java to use the Java bindings."
+	exit 1
+else
 	$(JAVAC) $(JFLAGS) $^
+endif
+
+# The following is a special case for evaluateMath because it requires JDK 1.5.
 
 evaluateMath.class: evaluateMath.java libSBMLHelper.java
-	$(JAVAC) $(JFLAGS) $^; \
-  if test $$? -ne 0; \
-    then echo "*** Sorry JDK 1.5 is required to compile evaluateMath ***"; fi
+ifeq "@JAVA@" ""
+	@echo "libSBML must be configured with --with-java to use the Java bindings."
+	exit 1
+else
+	@javaversion=`$(JAVA) -version 2>&1 | head -1`; \
+	if test `expr "$$javaversion" ':' '.*1\.5.*'` -eq 0; then \
+	  echo "*** JDK 1.5 is required to compile evaluateMath. ***"; \
+	else \
+	  $(JAVAC) $(JFLAGS) $^; \
+	fi
+endif
 
-printMath.class: printMath.java libSBMLHelper.java
-	$(JAVAC) $(JFLAGS) $^
-
-printSBML.class: printSBML.java libSBMLHelper.java
-	$(JAVAC) $(JFLAGS) $^
-
-readSBML.class: readSBML.java libSBMLHelper.java
-	$(JAVAC) $(JFLAGS) $^
-
-translateMath.class: translateMath.java libSBMLHelper.java
-	$(JAVAC) $(JFLAGS) $^
-
-validateSBML.class: validateSBML.java libSBMLHelper.java
-	$(JAVAC) $(JFLAGS) $^
+# The rest of the commands here are general-purpose things.
 
 clean:
 	/bin/rm -f $(classes) libSBMLHelper.class *~
 
 distclean: clean
 	/bin/rm Makefile
-
 
 # The following are generic 'make' targets that are not used in
 # this simple examples directory.
