Added preliminary support for Octave.

diff --git a/src/bindings/octave/Makefile.in b/src/bindings/octave/Makefile.in
--- a/src/bindings/octave/Makefile.in
+++ b/src/bindings/octave/Makefile.in
@@ -1,8 +1,8 @@
 ## @configure_input@
 ##
 ## \file    Makefile.in
-## \brief   Makefile template for libsbml bindings
-## \author  Mike Hucka
+## \brief   Makefile template for libsbml Octave bindings
+## \author  SBML Team <sbml-team@caltech.edu>
 ##
 ## $Id$
 ## $Source$
@@ -35,140 +35,113 @@ include @top_srcdir@/config/makefile-common-vars.mk
 
 # `srcdir' points to the current directory, but should be set by configure.
 # `subdir' must be set manually to the relative dir under srcdir.  Don't 
-# set `subdir' to an absolute path, or some `make' actions will fail.
+# set `subdir' to an absolute path, or some make actions will fail.
 
 srcdir  = @srcdir@
-thisdir = src/bindings
+thisdir = src/bindings/octave
 
-# Depending on the flags given during libSBML's configuration step, different
-# subdirectories will be added to the list of targets.
+# The Octave binding files are identical to the MATLAB version (so far),
+# but the commands to build them are different, and we have to keep the
+# binaries separate.  The approach taken here is to make symbolic links
+# to the Matlab files and then compile in the current directory.
 
-ifneq "$(MAKECMDGOALS)" "dist"
-  ifdef USE_PYTHON
-    subdirs = python
-  endif
-  ifdef USE_JAVA
-    subdirs += java
-  endif
-  ifdef USE_MATLAB
-    subdirs += matlab
-  endif
-  ifdef USE_OCTAVE
-    subdirs += octave
-  endif
-  ifdef USE_LISP
-    subdirs += lisp
-  endif
-  ifdef USE_PERL
-    subdirs += perl
-  endif
-else
-  # If `make dist' was given, include all subdirectories.
-  # subdirs = java lisp matlab python perl
-  # 2007-06-05 Lisp isn't currently working; disabling distribution for now.
-  subdirs = java matlab octave python perl
-endif
+matlab_sources = \
+  BuildTranslate_Win32.c \
+  BuildTranslate_Win32.m \
+  CheckAndConvert.m      \
+  Contents.m             \
+  README.txt             \
+  TranslateSBML.c        \
+  TranslateSBML.m        \
+  install.m              \
+  make.bat               \
+  test.xml
 
-swig_extras =    \
-  swig/layout.h  \
-  swig/layout.i  \
-  swig/libsbml.h \
-  swig/libsbml.i \
-  swig/swigdoc.py
+compiled_sources = TranslateSBML.c
 
-# Variables `subdirs', `headers', `sources', `libraries', `extra_CPPFLAGS',
-# `extra_CXXFLAGS', `extra_LDFLAGS' and `distfiles' are used by the default
-# rules in `makefile-common-actions.mk' included at the end.
+# This use of $(libraries) is slightly inconsistent with the other makefiles,
+# but for Octave, these object files act a lot like dynamic libraries and
+# we're installing them in the same place as the other libraries, so....
 
-distfiles = Makefile.in $(swig_extras)
+libraries = $(compiled_sources:.c=.$(OCTAVEEXT))
+
+subdirs = test
+
+# `distfiles' determines the files and directories included in a distribution.
+# `distfiles_exclude' is used to filter out specific items, so that even if
+# they appear in `distfiles', they will not be copied in the distribution.
+
+distfiles = Makefile.in
+
+# `extra_clean' and `extra_distclean' determine the files and directories
+# removed during "make clean" and "make distclean".
+
+extra_clean = TranslateSBML.$(OCTAVEEXT)
+
+extra_disclean = $(matlab_sources)
 
 
 # -----------------------------------------------------------------------------
 # Primary build actions
 # -----------------------------------------------------------------------------
 
-# The default rules in `makefile-common-actions.mk' know to interpret goals
-# of the form `foo-recursive' to run 'make foo' in directories defined in
-# variable `subdirs'.
+all: Makefile link-sources
+	make $(libraries)
 
-all: Makefile all-recursive 
+link-sources:
+	files='$(matlab_sources)'; for file in $$files; do\
+	  if ! test -f $$file; then \
+	    ln -s ../matlab/$$file; \
+	  fi; \
+	done
 
-
-# -----------------------------------------------------------------------------
-# Checking.
-# -----------------------------------------------------------------------------
+flags = $(MKOCTFILE_FLAGS) -I../.. -L../..
 
-check: all check-recursive
-
-
-# -----------------------------------------------------------------------------
-# Formatting documentation.
-# -----------------------------------------------------------------------------
-
-dvi: dvi-recursive
-
-pdf: pdf-recursive
-
-ps: ps-recursive
-
-info: info-recursive
-
-html: html-recursive
+%.$(OCTAVEEXT): %.c
+	$(MKOCTFILE) $(flags) $^ -lsbml $(MKOCTFILE_LIBS)
 
 
 # -----------------------------------------------------------------------------
 # Tags.
 # -----------------------------------------------------------------------------
 
-tags: tags-recursive
+octave-tags-extra-flags = *.c --lang=none --regex=@matlab-tags-regexp.txt *.m
+
+etags-command = $(ETAGS) $(ETAGSFLAGS) $(octave-tags-extra-flags)
+ctags-command = $(CTAGS) $(CTAGSFLAGS) $(octave-tags-extra-flags)
+
+tags: etags ctags
 
 
 # -----------------------------------------------------------------------------
-# Checking.
+# Targets for checking/testing.
 # -----------------------------------------------------------------------------
 
-install: all install-recursive
-
-installdirs: all installdirs-recursive
-
-uninstall: uninstall-recursive 
+check: check-recursive
 
 
 # -----------------------------------------------------------------------------
 # Installation.
 # -----------------------------------------------------------------------------
 
-install: install-recursive
+install: all install-libraries
 
-uninstall: uninstall-recursive 
+installdirs: all
 
-installdirs: installdirs-recursive
-
-
-# -----------------------------------------------------------------------------
-# Cleaning.
-# -----------------------------------------------------------------------------
-
-clean: clean-recursive
-
-distclean: distclean-recursive
-
-mostlyclean: mostlyclean-recursive
-
-maintainer-clean: maintainer-clean-recursive
+uninstall: uninstall-libraries
 
 
 # -----------------------------------------------------------------------------
 # Creating distribution (for libSBML maintainers only)
 # -----------------------------------------------------------------------------
 
-dist: dist-normal dist-recursive
+dist: all dist-normal dist-recursive
 
-distcheck: distcheck-recursive distcheck-normal
+distcheck: all distcheck-normal distcheck-recursive
 
 
 # -----------------------------------------------------------------------------
-# Common default rules.
+# Miscellaneous
 # -----------------------------------------------------------------------------
 
 include @top_srcdir@/config/makefile-common-actions.mk
