1. Improved make rules and dependencies for SWIG generated files.    Now, SWIG generated files are properly generated only when they need to be    newly created or updated (e.g. when configure's option for the layout extension changed)    or appropriate error messages are shown if SWIG is not installed.    Redundant updates can also be avoided by this change.
2. Modified 'clean-swigfiles' target to remove all SWIG generated files when this 
   target used by make (SWIG genreated files are not removed when 'clean' or 'distclean'
   used by make.)
   Basically, this target is automatically used by make when SWIG generated files need
   to be newly created or updated by SWIG.
   This may be helpful for developers of binding languages (at least for me) when they 
   want to clean SWIG generated files.

3. Added Visual Studio 2003 files to distfiles.

diff --git a/src/bindings/csharp/Makefile.in b/src/bindings/csharp/Makefile.in
--- a/src/bindings/csharp/Makefile.in
+++ b/src/bindings/csharp/Makefile.in
@@ -150,6 +150,19 @@ csharp_files     = $(wildcard $(outpath)/*.cs)
 csharp_files_win = $(wildcard $(outpath_win)/*.cs)
 csharp_files_win += libsbml_wrap-win.cpp
 
+vs2005_files = \
+  CSharp_binding_win32-xerces.sln  CSharp_binding_win32-xerces.vcproj \
+  CSharp_binding_win32-expat.sln CSharp_binding_win32-expat.vcproj \
+  CSharp_binding_win32-libxml.sln CSharp_binding_win32-libxml.vcproj \
+  CSharp_binding_TestRW.csproj CSharp_binding_cspDLL.csproj \
+  Properties/AssemblyInfo.cs
+
+vs2003_files = \
+  CSharp_binding_win32-xerces-vs2003.sln  CSharp_binding_win32-xerces-vs2003.vcproj \
+  CSharp_binding_win32-expat-vs2003.sln CSharp_binding_win32-expat-vs2003.vcproj \
+  CSharp_binding_win32-libxml-vs2003.sln CSharp_binding_win32-libxml-vs2003.vcproj \
+  CSharp_binding_TestRW-vs2003.csproj CSharp_binding_cspDLL-vs2003.csproj 
+
 # `distfiles' determines the files and directories included in a
 # distribution.  The strategy here is that we include the output of SWIG
 # (libsbml_wrap.cpp, libsbml_wrap-win.cpp and the csharp files) but not the 
@@ -157,11 +170,7 @@ csharp_files_win += libsbml_wrap-win.cpp
 
 distfiles   = $(sources) $(extra_sources) $(check_sources) \
   Makefile.in $(csharp_files) $(csharp_files_win) \
-  CSharp_binding_win32-xerces.sln  CSharp_binding_win32-xerces.vcproj \
-  CSharp_binding_win32-expat.sln CSharp_binding_win32-expat.vcproj \
-  CSharp_binding_win32-libxml.sln CSharp_binding_win32-libxml.vcproj \
-  CSharp_binding_TestRW.csproj CSharp_binding_cspDLL.csproj \
-  createInclude.bat Properties/AssemblyInfo.cs
+  $(vs2003_files) $(vs2005_files) createInclude.bat 
 
 tmpfiles = $(wildcard test*.xml*)
 
@@ -170,33 +179,8 @@ tmpfiles = $(wildcard test*.xml*)
 
 extra_clean = $(csproxy_lib) $(dllimport_lib) $(check_runner_exe) $(tmpfiles)
 
-extra_distclean = $outpath
+extra_distclean = 
 
-
-# -----------------------------------------------------------------------------
-# Primary build actions
-# -----------------------------------------------------------------------------
-
-# This whole setup is more or less custom and mostly doesn't use the common
-# build directives of `makefile-common-actions.mk'.
-
-.SUFFIXES:
-.SUFFIXES: .i .cpp .h .cs .dll .o .obj .so .dylib
-
-# The default action is to remake everything.
-
-ifdef USE_CSHARP
-all: Makefile $(libraries)
-else
-all:
-	@echo
-	@echo "Reconfigure libSBML using --with-csharp to enable CSharp support."; 
-	@echo "(--with-cli-interpreter=path" and/or --with-csharp-compiler=path may be required.)";
-	@echo
-	@exit 1
-endif
-
-# The rest here is for developers and maintainers.  Recipients of the
 # library distributions shouldn't have to run SWIG because we provide the
 # wrapper file ready-made.
 
@@ -214,15 +198,6 @@ main_sources = \
 ifeq "$(HOST_TYPE)" "darwin"
   platform_link_flags = -bundle
 endif
-
-# The dependencies that follow are an awful tangle.  I wish I could find a
-# way to simplify this.  The critical point is that we don't want to put a
-# list naming all the .cs files explicitly in this Makefile, because any
-# change to the output of SWIG could cause a change in the .cs files it
-# produces and render obsolete any list contained here.  So we have to try
-# to wildcard the files, but that in itself is impossible until they're
-# generated by running SWIG.  Ugh.
-#
 
 # 
 # command line options for Mono
@@ -250,14 +225,72 @@ ifeq (cscc,$(findstring cscc,$(shell $(CSHARP_COMPILER) --version 2>&1)))
   CSC_OPT_REF    = -l
 endif
 
+
+# -----------------------------------------------------------------------------
+# Primary build actions
+# -----------------------------------------------------------------------------
+
+# This whole setup is more or less custom and mostly doesn't use the common
+# build directives of `makefile-common-actions.mk'.
+
+.SUFFIXES:
+.SUFFIXES: .i .cpp .h .cs .dll .o .obj .so .dylib
+
+# The default action is to remake everything.
+
+ifdef USE_CSHARP
+all: Makefile check_swigfile_consistency
+else
+all:
+	@echo
+	@echo "Reconfigure libSBML using --with-csharp to enable CSharp support."; 
+	@echo "(--with-cli-interpreter=path" and/or --with-csharp-compiler=path may be required.)";
+	@echo
+	@exit 1
+endif
+
+# The rest here is for developers and maintainers.  Recipients of the
+# dependencies that follow are an awful tangle.  I wish I could find a
+# way to simplify this.  The critical point is that we don't want to put a
+# list naming all the .cs files explicitly in this Makefile, because any
+# change to the output of SWIG could cause a change in the .cs files it
+# produces and render obsolete any list contained here.  So we have to try
+# to wildcard the files, but that in itself is impossible until they're
+# generated by running SWIG.  Ugh.
+#
+
+#
+# Recreates SWIG files when one of the following conditions is true:
+#
+#  (1) libsbml_wrap.cpp does not exist
+#  (2) libsbml_wrap.cpp exists, but the file is not consistent with the current USE_LAYOUT value. 
+#
+check_swigfile_consistency:
+ifeq (yes, $(findstring yes,$(shell test -f libsbml_wrap.cpp && echo yes)))
+  ifdef USE_LAYOUT
+    ifneq (getListOfLayouts, $(findstring getListOfLayouts,$(shell grep getListOfLayouts libsbml_wrap.cpp)))
+	$(MAKE) -$(MAKEFLAGS) recreate_csharp_files
+    endif
+  else
+    ifeq (getListOfLayouts, $(findstring getListOfLayouts,$(shell grep getListOfLayouts libsbml_wrap.cpp)))
+	$(MAKE) -$(MAKEFLAGS) recreate_csharp_files
+    endif
+  endif # USE_LAYOUT
+else
+	$(MAKE) -$(MAKEFLAGS) recreate_csharp_files
+endif   # ifeq (yes...
+	$(MAKE) -$(MAKEFLAGS) $(csproxy_lib)
+
+
 $(csproxy_lib): $(outpath)/libsbml.cs $(dllimport_lib)
-	$(MAKE) -$(MAKEFLAGS) $(dllimport_lib)
 	"$(CSHARP_COMPILER)" $(CSC_OPT_SHARED) $(CSC_OPT_OUTPUT)$(csproxy_lib) $(outpath)/*.cs
 
+
 $(outpath)/libsbml.cs: libsbml_wrap.cpp 
-ifeq "$(csharp_files)" ""
-	$(MAKE) -$(MAKEFLAGS) recreate_csharp_files
-endif
+	@if ! test -f "$(outpath)/libsbml.cs"; then \
+		$(MAKE) -$(MAKEFLAGS) recreate_csharp_files; \
+	fi
+
 
 # libsbml_wrap.cpp (for non-Windows) and libsbml_wrap-win.cpp (for Windows)
 # stand-in for the .cs files.  Their creation results in the creation of the .cs 
@@ -281,14 +314,18 @@ else
 	@exit 1
 endif
 
+
 # If USE_SWIG is *not* in effect, things get tricky.  If the last run was
 # made with --enable-layout and this one isn't, or vice-versa, the swig
 # wrap files will be wrong for this run.  However, you can't tell just by
 # looking at file mod times, so you can't use normal make dependencies.  So
 # we do this grungy trick of looking at the file to see what's inside.
 
-ifdef USE_LAYOUT
 recreate_csharp_files:;
+ifdef USE_SWIG
+	$(MAKE) -$(MAKEFLAGS) clean-swigfiles $(outpath)
+else
+  ifdef USE_LAYOUT
 	@if test -z "`grep getListOfLayouts libsbml_wrap.cpp`"; then \
 	  echo ;\
 	  echo "The existing libsbml_wrap.cpp file lacks the layout code."; \
@@ -298,17 +335,22 @@ recreate_csharp_files:;
 	else \
 	  $(MAKE) -$(MAKEFLAGS) $(outpath); \
 	fi
-
-else # not USE_LAYOUT
-recreate_csharp_files:;
+  else  # not USE_LAYOUT
 	@if test -n "`grep getListOfLayouts libsbml_wrap.cpp`"; then \
-	  $(MAKE) -$(MAKEFLAGS) clean-swigfiles; \
+	  echo ;\
+	  echo "The existing libsbml_wrap.cpp file contains the layout code."; \
+	  echo "Reconfigure --with-swig to correct this."; \
+	  echo ;\
+	  exit 1; \
+	else \
+	  $(MAKE) -$(MAKEFLAGS) $(outpath); \
 	fi
-	$(MAKE) -$(MAKEFLAGS) $(outpath)
-endif # USE_LAYOUT
+  endif # USE_LAYOUT  
+endif #USE_SWIG
 
-clean-swigfiles:
-	rm -rf $(outdir)
+
+clean-swigfiles: clean
+	-rm -rf $(outpath) $(outpath_win) libsbml_wrap.cpp libsbml_wrap-win.cpp
 
 
 # -----------------------------------------------------------------------------
@@ -317,7 +359,7 @@ clean-swigfiles:
 
 check_runner_exe = $(check_runner_source:.cs=.exe)
 
-$(check_runner_exe): Makefile $(libraries) $(check_runner_source) 
+$(check_runner_exe): Makefile check_swigfile_consistency $(check_runner_source) 
 	"$(CSHARP_COMPILER)" $(CSC_OPT_EXE) $(CSC_OPT_OUTPUT)$(check_runner_exe) \
 	$(CSC_OPT_REF)$(csproxy_lib) $(check_runner_source)
 
